Jorge Sánchez Cerezo
\
email: jsc124@alu.ua.es / jorsancere@gmail.com
\
Grupo 2

# Pandas

## 6.1 Creating DataFrames

Lo primero de todo, ya hemos instalado la librería pandas, y ahora, vamos a crear nuestro "DataFrame" de diversas formas.
Un DataFrame es una tabla NO RELACIONADA en la que podemos introducir datos sobre diferentes aspectos, gracias a esta librería, podremos trabajar con estas tablas.

### 6.1.1. Creating a DataFrame from a dictionary

Gracias a la función pd.DataFrame(), podemos crear nuestros DataFrame, ahora, nuestro DataFrame (vamos a hacerlo de jugadores de la NBA, con algunas estadisticas (como PPG, Rebotes y asistencias) y datos (equipos y posición))

In [1]:
import pandas as pd

datos = {
    'Equipo': [
        'Nuggets', 'Mavericks', 'Bucks', 'Thunder', 'Bulls', 
        'Lakers', 'Suns', 'Grizzlies', 'Warriors', 'Timberwolves', 
        'Lakers', 'Spurs', 'Lakers', 'Bulls', 'Bulls'
    ],
    'Nombre': [
        'Nikola Jokic', 'Luka Doncic', 'Giannis Antetokounmpo', 'Shai Gilgeous-Alexander', 'Michael Jordan', 
        'LeBron James', 'Kevin Durant', 'Ja Morant', 'Stephen Curry', 'Anthony Edwards', 
        'Kobe Bryant', 'Victor Wembanyama', 'Shaquille O/Neal', 'Derrick Rose', 'Dennis Rodman'
    ],
    'Posicion': [
        'Pívot', 'Base', 'Ala-Pívot', 'Base', 'Escolta', 
        'Alero', 'Alero', 'Base', 'Base', 'Escolta', 
        'Escolta', 'Pívot', 'Pívot', 'Base', 'Ala-Pívot'
    ],
    'Puntos': [29.7, 33.9, 30.4, 30.1, 30.1, 25.7, 27.1, 25.1, 26.4, 25.9, 25.0, 21.4, 23.7, 17.7, 7.3],
    'Rebotes': [13.7, 9.2, 11.5, 5.5, 6.2, 7.3, 6.6, 5.6, 4.5, 5.4, 5.2, 10.6, 10.9, 3.3, 13.1],
    'Asistencias': [11.7, 9.8, 6.5, 6.2, 5.3, 8.3, 5.0, 8.1, 5.1, 5.1, 4.7, 3.9, 2.5, 5.2, 1.8],
    'Mismo_Equipo': [
        [], [], [], [], [13, 14], 
        [10, 12], [], [], [], [], 
        [5, 12], [], [5, 10], [4, 14], [4, 13]
    ],
    'Amigos': [
        [1, 2, 11], [0, 8, 11, 2], [0, 1, 3, 6], [2, 7, 9], [10, 5, 12],
        [8, 6, 4, 1], [8, 5, 2, 0], [3, 8, 9, 13], [5, 6, 1, 7], [3, 7, 11],
        [4, 13, 1], [0, 1, 9], [14, 4, 0], [7, 10, 8], [12, 5]
    ]
}

# Crear el DataFrame
df_nba = pd.DataFrame(datos)

# Mostrar el DataFrame
print("--- DataFrame NBA ---")
df_nba

--- DataFrame NBA ---

,Equipo,Nombre,Posicion,Puntos,Rebotes,Asistencias,Mismo_Equipo,Amigos
0,Nuggets,Nikola Jokic,Pívot,29.7,13.7,11.7,[],"[1, 2, 11]"
1,Mavericks,Luka Doncic,Base,33.9,9.2,9.8,[],"[0, 8, 11, 2]"
2,Bucks,Giannis Antetokounmpo,Ala-Pívot,30.4,11.5,6.5,[],"[0, 1, 3, 6]"
3,Thunder,Shai Gilgeous-Alexander,Base,30.1,5.5,6.2,[],"[2, 7, 9]"
4,Bulls,Michael Jordan,Escolta,30.1,6.2,5.3,"[13, 14]","[10, 5, 12]"
5,Lakers,LeBron James,Alero,25.7,7.3,8.3,"[10, 12]","[8, 6, 4, 1]"
6,Suns,Kevin Durant,Alero,27.1,6.6,5.0,[],"[8, 5, 2, 0]"
7,Grizzlies,Ja Morant,Base,25.1,5.6,8.1,[],"[3, 8, 9, 13]"
8,Warriors,Stephen Curry,Base,26.4,4.5,5.1,[],"[5, 6, 1, 7]"
9,Timberwolves,Anthony Edwards,Escolta,25.9,5.4,5.1,[],"[3, 7, 11]"
10,Lakers,Kobe Bryant,Escolta,25.0,5.2,4.7,"[5, 12]","[4, 13, 1]"
11,Spurs,Victor Wembanyama,Pívot,21.4,10.6,3.9,[],"[0, 1, 9]"
12,Lakers,Shaquille O/Neal,Pívot,23.7,10.9,2.5,"[5, 10]","[14, 4, 0]"
13,Bulls,Derrick Rose,Base,17.7,3.3,5.2,"[4, 14]","[7, 10, 8]"
14,Bulls,Dennis Rodman,Ala-Pívot,7.3,13.1,1.8,"[4, 13]","[12, 5]"

### 6.1.2. Creating a DataFrame from a list of dictionaries

También es posible crear nuestro DataFrame con una lista de diccionarios:

In [2]:
import pandas as pd

# Vamos a crear nuestra lista con todos los diccionarios
datos_nba = [
    {"Nombre": "Nikola Jokic", "Equipo": "Nuggets", "Posicion": "Pívot", "Puntos": 29.7, "Rebotes": 13.7, "Asistencias": 11.7, "Mismo_Equipo": [], "Amigos": [1, 2, 11]},
    {"Nombre": "Luka Doncic", "Equipo": "Mavericks", "Posicion": "Base", "Puntos": 33.9, "Rebotes": 9.2, "Asistencias": 9.8, "Mismo_Equipo": [], "Amigos": [0, 8, 11, 2]},
    {"Nombre": "Giannis Antetokounmpo", "Equipo": "Bucks", "Posicion": "Ala-Pívot", "Puntos": 30.4, "Rebotes": 11.5, "Asistencias": 6.5, "Mismo_Equipo": [], "Amigos": [0, 1, 3, 6]},
    {"Nombre": "Shai Gilgeous-Alexander", "Equipo": "Thunder", "Posicion": "Base", "Puntos": 30.1, "Rebotes": 5.5, "Asistencias": 6.2, "Mismo_Equipo": [], "Amigos": [2, 7, 9]},
    {"Nombre": "Michael Jordan", "Equipo": "Bulls", "Posicion": "Escolta", "Puntos": 30.1, "Rebotes": 6.2, "Asistencias": 5.3, "Mismo_Equipo": [13, 14], "Amigos": [10, 5, 12]},
    {"Nombre": "LeBron James", "Equipo": "Lakers", "Posicion": "Alero", "Puntos": 25.7, "Rebotes": 7.3, "Asistencias": 8.3, "Mismo_Equipo": [10, 12], "Amigos": [8, 6, 4, 1]},
    {"Nombre": "Kevin Durant", "Equipo": "Suns", "Posicion": "Alero", "Puntos": 27.1, "Rebotes": 6.6, "Asistencias": 5.0, "Mismo_Equipo": [], "Amigos": [8, 5, 2, 0]},
    {"Nombre": "Ja Morant", "Equipo": "Grizzlies", "Posicion": "Base", "Puntos": 25.1, "Rebotes": 5.6, "Asistencias": 8.1, "Mismo_Equipo": [], "Amigos": [3, 8, 9, 13]},
    {"Nombre": "Stephen Curry", "Equipo": "Warriors", "Posicion": "Base", "Puntos": 26.4, "Rebotes": 4.5, "Asistencias": 5.1, "Mismo_Equipo": [], "Amigos": [5, 6, 1, 7]},
    {"Nombre": "Anthony Edwards", "Equipo": "Timberwolves", "Posicion": "Escolta", "Puntos": 25.9, "Rebotes": 5.4, "Asistencias": 5.1, "Mismo_Equipo": [], "Amigos": [3, 7, 11]},
    {"Nombre": "Kobe Bryant", "Equipo": "Lakers", "Posicion": "Escolta", "Puntos": 25.0, "Rebotes": 5.2, "Asistencias": 4.7, "Mismo_Equipo": [5, 12], "Amigos": [4, 13, 1]},
    {"Nombre": "Victor Wembanyama", "Equipo": "Spurs", "Posicion": "Pívot", "Puntos": 21.4, "Rebotes": 10.6, "Asistencias": 3.9, "Mismo_Equipo": [], "Amigos": [0, 1, 9]},
    {"Nombre": "Shaquille O/Neal", "Equipo": "Lakers", "Posicion": "Pívot", "Puntos": 23.7, "Rebotes": 10.9, "Asistencias": 2.5, "Mismo_Equipo": [5, 10], "Amigos": [14, 4, 0]},
    {"Nombre": "Derrick Rose", "Equipo": "Bulls", "Posicion": "Base", "Puntos": 17.7, "Rebotes": 3.3, "Asistencias": 5.2, "Mismo_Equipo": [4, 14], "Amigos": [7, 10, 8]},
    {"Nombre": "Dennis Rodman", "Equipo": "Bulls", "Posicion": "Ala-Pívot", "Puntos": 7.3, "Rebotes": 13.1, "Asistencias": 1.8, "Mismo_Equipo": [4, 13], "Amigos": [12, 5]}
]

# Creamos el DataFrame
df_nba = pd.DataFrame(datos_nba)

# Mostrar el resultado
print("--- DataFrame NBA ---")
df_nba

--- DataFrame NBA ---

,Nombre,Equipo,Posicion,Puntos,Rebotes,Asistencias,Mismo_Equipo,Amigos
0,Nikola Jokic,Nuggets,Pívot,29.7,13.7,11.7,[],"[1, 2, 11]"
1,Luka Doncic,Mavericks,Base,33.9,9.2,9.8,[],"[0, 8, 11, 2]"
2,Giannis Antetokounmpo,Bucks,Ala-Pívot,30.4,11.5,6.5,[],"[0, 1, 3, 6]"
3,Shai Gilgeous-Alexander,Thunder,Base,30.1,5.5,6.2,[],"[2, 7, 9]"
4,Michael Jordan,Bulls,Escolta,30.1,6.2,5.3,"[13, 14]","[10, 5, 12]"
5,LeBron James,Lakers,Alero,25.7,7.3,8.3,"[10, 12]","[8, 6, 4, 1]"
6,Kevin Durant,Suns,Alero,27.1,6.6,5.0,[],"[8, 5, 2, 0]"
7,Ja Morant,Grizzlies,Base,25.1,5.6,8.1,[],"[3, 8, 9, 13]"
8,Stephen Curry,Warriors,Base,26.4,4.5,5.1,[],"[5, 6, 1, 7]"
9,Anthony Edwards,Timberwolves,Escolta,25.9,5.4,5.1,[],"[3, 7, 11]"
10,Kobe Bryant,Lakers,Escolta,25.0,5.2,4.7,"[5, 12]","[4, 13, 1]"
11,Victor Wembanyama,Spurs,Pívot,21.4,10.6,3.9,[],"[0, 1, 9]"
12,Shaquille O/Neal,Lakers,Pívot,23.7,10.9,2.5,"[5, 10]","[14, 4, 0]"
13,Derrick Rose,Bulls,Base,17.7,3.3,5.2,"[4, 14]","[7, 10, 8]"
14,Dennis Rodman,Bulls,Ala-Pívot,7.3,13.1,1.8,"[4, 13]","[12, 5]"

### 6.1.3. Creating a DataFrame from a list of lists

Otra forma de crear un DataFrame es con una lista de listas, mas tarde, asignaremos los nombres de las columnas:

In [3]:
import pandas as pd

# Datos con la estructura de lista de listas (matriz)
# Formato: [Nombre, Equipo, Posicion, Puntos, Rebotes, Asistencias, Mismo_Equipo, Amigos]
data = [
    ['Nikola Jokic', 'Nuggets', 'Pívot', 29.7, 13.7, 11.7, [], [1, 2, 11]],
    ['Luka Doncic', 'Mavericks', 'Base', 33.9, 9.2, 9.8, [], [0, 8, 11, 2]],
    ['Giannis Antetokounmpo', 'Bucks', 'Ala-Pívot', 30.4, 11.5, 6.5, [], [0, 1, 3, 6]],
    ['Shai Gilgeous-Alexander', 'Thunder', 'Base', 30.1, 5.5, 6.2, [], [2, 7, 9]],
    ['Michael Jordan', 'Bulls', 'Escolta', 30.1, 6.2, 5.3, [13, 14], [10, 5, 12]],
    ['LeBron James', 'Lakers', 'Alero', 25.7, 7.3, 8.3, [10, 12], [8, 6, 4, 1]],
    ['Kevin Durant', 'Suns', 'Alero', 27.1, 6.6, 5.0, [], [8, 5, 2, 0]],
    ['Ja Morant', 'Grizzlies', 'Base', 25.1, 5.6, 8.1, [], [3, 8, 9, 13]],
    ['Stephen Curry', 'Warriors', 'Base', 26.4, 4.5, 5.1, [], [5, 6, 1, 7]],
    ['Anthony Edwards', 'Timberwolves', 'Escolta', 25.9, 5.4, 5.1, [], [3, 7, 11]],
    ['Kobe Bryant', 'Lakers', 'Escolta', 25.0, 5.2, 4.7, [5, 12], [4, 13, 1]],
    ['Victor Wembanyama', 'Spurs', 'Pívot', 21.4, 10.6, 3.9, [], [0, 1, 9]],
    ['Shaquille O/Neal', 'Lakers', 'Pívot', 23.7, 10.9, 2.5, [5, 10], [14, 4, 0]],
    ['Derrick Rose', 'Bulls', 'Base', 17.7, 3.3, 5.2, [4, 14], [7, 10, 8]],
    ['Dennis Rodman', 'Bulls', 'Ala-Pívot', 7.3, 13.1, 1.8, [4, 13], [12, 5]]
]

# Creación del DataFrame
df = pd.DataFrame(data, columns = ['Nombre', 'Equipo', 'Posicion', 'Puntos', 'Rebotes', 'Asistencias', 'Mismo_Equipo', 'Amigos'])

# Mostrar el DataFrame
print("--- DataFrame NBA (Lista de Listas) ---")
df

--- DataFrame NBA (Lista de Listas) ---

,Nombre,Equipo,Posicion,Puntos,Rebotes,Asistencias,Mismo_Equipo,Amigos
0,Nikola Jokic,Nuggets,Pívot,29.7,13.7,11.7,[],"[1, 2, 11]"
1,Luka Doncic,Mavericks,Base,33.9,9.2,9.8,[],"[0, 8, 11, 2]"
2,Giannis Antetokounmpo,Bucks,Ala-Pívot,30.4,11.5,6.5,[],"[0, 1, 3, 6]"
3,Shai Gilgeous-Alexander,Thunder,Base,30.1,5.5,6.2,[],"[2, 7, 9]"
4,Michael Jordan,Bulls,Escolta,30.1,6.2,5.3,"[13, 14]","[10, 5, 12]"
5,LeBron James,Lakers,Alero,25.7,7.3,8.3,"[10, 12]","[8, 6, 4, 1]"
6,Kevin Durant,Suns,Alero,27.1,6.6,5.0,[],"[8, 5, 2, 0]"
7,Ja Morant,Grizzlies,Base,25.1,5.6,8.1,[],"[3, 8, 9, 13]"
8,Stephen Curry,Warriors,Base,26.4,4.5,5.1,[],"[5, 6, 1, 7]"
9,Anthony Edwards,Timberwolves,Escolta,25.9,5.4,5.1,[],"[3, 7, 11]"
10,Kobe Bryant,Lakers,Escolta,25.0,5.2,4.7,"[5, 12]","[4, 13, 1]"
11,Victor Wembanyama,Spurs,Pívot,21.4,10.6,3.9,[],"[0, 1, 9]"
12,Shaquille O/Neal,Lakers,Pívot,23.7,10.9,2.5,"[5, 10]","[14, 4, 0]"
13,Derrick Rose,Bulls,Base,17.7,3.3,5.2,"[4, 14]","[7, 10, 8]"
14,Dennis Rodman,Bulls,Ala-Pívot,7.3,13.1,1.8,"[4, 13]","[12, 5]"

## 6.2. Accessing DataFrames

Con nuestros DataFrames, podemos acceder tanto a nuestras columnas, filas o incluso celdas:

## 6.2.1. Accessing individual columns

Podemos acceder a las columnas mediante su nombre:

In [4]:
import pandas as pd

datos = {
    'Equipo': [
        'Nuggets', 'Mavericks', 'Bucks', 'Thunder', 'Bulls', 
        'Lakers', 'Suns', 'Grizzlies', 'Warriors', 'Timberwolves', 
        'Lakers', 'Spurs', 'Lakers', 'Bulls', 'Bulls'
    ],
    'Nombre': [
        'Nikola Jokic', 'Luka Doncic', 'Giannis Antetokounmpo', 'Shai Gilgeous-Alexander', 'Michael Jordan', 
        'LeBron James', 'Kevin Durant', 'Ja Morant', 'Stephen Curry', 'Anthony Edwards', 
        'Kobe Bryant', 'Victor Wembanyama', 'Shaquille O/Neal', 'Derrick Rose', 'Dennis Rodman'
    ],
    'Posicion': [
        'Pívot', 'Base', 'Ala-Pívot', 'Base', 'Escolta', 
        'Alero', 'Alero', 'Base', 'Base', 'Escolta', 
        'Escolta', 'Pívot', 'Pívot', 'Base', 'Ala-Pívot'
    ],
    'Puntos': [29.7, 33.9, 30.4, 30.1, 30.1, 25.7, 27.1, 25.1, 26.4, 25.9, 25.0, 21.4, 23.7, 17.7, 7.3],
    'Rebotes': [13.7, 9.2, 11.5, 5.5, 6.2, 7.3, 6.6, 5.6, 4.5, 5.4, 5.2, 10.6, 10.9, 3.3, 13.1],
    'Asistencias': [11.7, 9.8, 6.5, 6.2, 5.3, 8.3, 5.0, 8.1, 5.1, 5.1, 4.7, 3.9, 2.5, 5.2, 1.8],
    'Mismo_Equipo': [
        [], [], [], [], [13, 14], 
        [10, 12], [], [], [], [], 
        [5, 12], [], [5, 10], [4, 14], [4, 13]
    ],
    'Amigos': [
        [1, 2, 11], [0, 8, 11, 2], [0, 1, 3, 6], [2, 7, 9], [10, 5, 12],
        [8, 6, 4, 1], [8, 5, 2, 0], [3, 8, 9, 13], [5, 6, 1, 7], [3, 7, 11],
        [4, 13, 1], [0, 1, 9], [14, 4, 0], [7, 10, 8], [12, 5]
    ]
}

# Crear el DataFrame
df_nba = pd.DataFrame(datos)

# Mostrar el DataFrame
print("--- DataFrame NBA ---")
print(df_nba['Puntos'])

--- DataFrame NBA ---
0     29.7
1     33.9
2     30.4
3     30.1
4     30.1
5     25.7
6     27.1
7     25.1
8     26.4
9     25.9
10    25.0
11    21.4
12    23.7
13    17.7
14     7.3
Name: Puntos, dtype: float64

### 6.2.2. Accessing individual rows

Lo mismo pasa con las filas, solo que debemos utilizar la funcion iloc[]:

In [5]:
import pandas as pd

datos = {
    'Equipo': [
        'Nuggets', 'Mavericks', 'Bucks', 'Thunder', 'Bulls', 
        'Lakers', 'Suns', 'Grizzlies', 'Warriors', 'Timberwolves', 
        'Lakers', 'Spurs', 'Lakers', 'Bulls', 'Bulls'
    ],
    'Nombre': [
        'Nikola Jokic', 'Luka Doncic', 'Giannis Antetokounmpo', 'Shai Gilgeous-Alexander', 'Michael Jordan', 
        'LeBron James', 'Kevin Durant', 'Ja Morant', 'Stephen Curry', 'Anthony Edwards', 
        'Kobe Bryant', 'Victor Wembanyama', 'Shaquille O/Neal', 'Derrick Rose', 'Dennis Rodman'
    ],
    'Posicion': [
        'Pívot', 'Base', 'Ala-Pívot', 'Base', 'Escolta', 
        'Alero', 'Alero', 'Base', 'Base', 'Escolta', 
        'Escolta', 'Pívot', 'Pívot', 'Base', 'Ala-Pívot'
    ],
    'Puntos': [29.7, 33.9, 30.4, 30.1, 30.1, 25.7, 27.1, 25.1, 26.4, 25.9, 25.0, 21.4, 23.7, 17.7, 7.3],
    'Rebotes': [13.7, 9.2, 11.5, 5.5, 6.2, 7.3, 6.6, 5.6, 4.5, 5.4, 5.2, 10.6, 10.9, 3.3, 13.1],
    'Asistencias': [11.7, 9.8, 6.5, 6.2, 5.3, 8.3, 5.0, 8.1, 5.1, 5.1, 4.7, 3.9, 2.5, 5.2, 1.8],
    'Mismo_Equipo': [
        [], [], [], [], [13, 14], 
        [10, 12], [], [], [], [], 
        [5, 12], [], [5, 10], [4, 14], [4, 13]
    ],
    'Amigos': [
        [1, 2, 11], [0, 8, 11, 2], [0, 1, 3, 6], [2, 7, 9], [10, 5, 12],
        [8, 6, 4, 1], [8, 5, 2, 0], [3, 8, 9, 13], [5, 6, 1, 7], [3, 7, 11],
        [4, 13, 1], [0, 1, 9], [14, 4, 0], [7, 10, 8], [12, 5]
    ]
}

# Crear el DataFrame
df_nba = pd.DataFrame(datos)

# Mostrar el DataFrame
print("--- DataFrame NBA ---")
print(df.iloc[8])

--- DataFrame NBA ---
Nombre          Stephen Curry
Equipo               Warriors
Posicion                 Base
Puntos                   26.4
Rebotes                   4.5
Asistencias               5.1
Mismo_Equipo               []
Amigos           [5, 6, 1, 7]
Name: 8, dtype: object

### 6.2.3. Accessing individual cells

Para celdas, tenemos que introducir en el iloc[][], la fila y columna respectivamente:

In [6]:
import pandas as pd

datos = {
    'Equipo': [
        'Nuggets', 'Mavericks', 'Bucks', 'Thunder', 'Bulls', 
        'Lakers', 'Suns', 'Grizzlies', 'Warriors', 'Timberwolves', 
        'Lakers', 'Spurs', 'Lakers', 'Bulls', 'Bulls'
    ],
    'Nombre': [
        'Nikola Jokic', 'Luka Doncic', 'Giannis Antetokounmpo', 'Shai Gilgeous-Alexander', 'Michael Jordan', 
        'LeBron James', 'Kevin Durant', 'Ja Morant', 'Stephen Curry', 'Anthony Edwards', 
        'Kobe Bryant', 'Victor Wembanyama', 'Shaquille O/Neal', 'Derrick Rose', 'Dennis Rodman'
    ],
    'Posicion': [
        'Pívot', 'Base', 'Ala-Pívot', 'Base', 'Escolta', 
        'Alero', 'Alero', 'Base', 'Base', 'Escolta', 
        'Escolta', 'Pívot', 'Pívot', 'Base', 'Ala-Pívot'
    ],
    'Puntos': [29.7, 33.9, 30.4, 30.1, 30.1, 25.7, 27.1, 25.1, 26.4, 25.9, 25.0, 21.4, 23.7, 17.7, 7.3],
    'Rebotes': [13.7, 9.2, 11.5, 5.5, 6.2, 7.3, 6.6, 5.6, 4.5, 5.4, 5.2, 10.6, 10.9, 3.3, 13.1],
    'Asistencias': [11.7, 9.8, 6.5, 6.2, 5.3, 8.3, 5.0, 8.1, 5.1, 5.1, 4.7, 3.9, 2.5, 5.2, 1.8],
    'Mismo_Equipo': [
        [], [], [], [], [13, 14], 
        [10, 12], [], [], [], [], 
        [5, 12], [], [5, 10], [4, 14], [4, 13]
    ],
    'Amigos': [
        [1, 2, 11], [0, 8, 11, 2], [0, 1, 3, 6], [2, 7, 9], [10, 5, 12],
        [8, 6, 4, 1], [8, 5, 2, 0], [3, 8, 9, 13], [5, 6, 1, 7], [3, 7, 11],
        [4, 13, 1], [0, 1, 9], [14, 4, 0], [7, 10, 8], [12, 5]
    ]
}

# Crear el DataFrame
df_nba = pd.DataFrame(datos)

# Mostrar el DataFrame
print("--- DataFrame NBA ---")
print(df.iloc[0]['Nombre'])

--- DataFrame NBA ---
Nikola Jokic

## 6.3. Operations on DataFrames

odemos hacer varias operaciones sobre nuestro dataframe para obtener los resultados  que queramos

### 6.3.1. Filtering DataFrames

Podemos filtrar nuestro resultado introduciendo condiciones:

In [7]:
import pandas as pd

datos = {
    'Equipo': [
        'Nuggets', 'Mavericks', 'Bucks', 'Thunder', 'Bulls', 
        'Lakers', 'Suns', 'Grizzlies', 'Warriors', 'Timberwolves', 
        'Lakers', 'Spurs', 'Lakers', 'Bulls', 'Bulls'
    ],
    'Nombre': [
        'Nikola Jokic', 'Luka Doncic', 'Giannis Antetokounmpo', 'Shai Gilgeous-Alexander', 'Michael Jordan', 
        'LeBron James', 'Kevin Durant', 'Ja Morant', 'Stephen Curry', 'Anthony Edwards', 
        'Kobe Bryant', 'Victor Wembanyama', 'Shaquille O/Neal', 'Derrick Rose', 'Dennis Rodman'
    ],
    'Posicion': [
        'Pívot', 'Base', 'Ala-Pívot', 'Base', 'Escolta', 
        'Alero', 'Alero', 'Base', 'Base', 'Escolta', 
        'Escolta', 'Pívot', 'Pívot', 'Base', 'Ala-Pívot'
    ],
    'Puntos': [29.7, 33.9, 30.4, 30.1, 30.1, 25.7, 27.1, 25.1, 26.4, 25.9, 25.0, 21.4, 23.7, 17.7, 7.3],
    'Rebotes': [13.7, 9.2, 11.5, 5.5, 6.2, 7.3, 6.6, 5.6, 4.5, 5.4, 5.2, 10.6, 10.9, 3.3, 13.1],
    'Asistencias': [11.7, 9.8, 6.5, 6.2, 5.3, 8.3, 5.0, 8.1, 5.1, 5.1, 4.7, 3.9, 2.5, 5.2, 1.8],
    'Mismo_Equipo': [
        [], [], [], [], [13, 14], 
        [10, 12], [], [], [], [], 
        [5, 12], [], [5, 10], [4, 14], [4, 13]
    ],
    'Amigos': [
        [1, 2, 11], [0, 8, 11, 2], [0, 1, 3, 6], [2, 7, 9], [10, 5, 12],
        [8, 6, 4, 1], [8, 5, 2, 0], [3, 8, 9, 13], [5, 6, 1, 7], [3, 7, 11],
        [4, 13, 1], [0, 1, 9], [14, 4, 0], [7, 10, 8], [12, 5]
    ]
}

# Crear el DataFrame
df_nba = pd.DataFrame(datos)
df_filtro = df[df['Puntos'] > 25] #Jugadores con mas de 25 puntos
# Mostrar el DataFrame
print("--- DataFrame NBA ---")
df_filtro

--- DataFrame NBA ---

,Nombre,Equipo,Posicion,Puntos,Rebotes,Asistencias,Mismo_Equipo,Amigos
0,Nikola Jokic,Nuggets,Pívot,29.7,13.7,11.7,[],"[1, 2, 11]"
1,Luka Doncic,Mavericks,Base,33.9,9.2,9.8,[],"[0, 8, 11, 2]"
2,Giannis Antetokounmpo,Bucks,Ala-Pívot,30.4,11.5,6.5,[],"[0, 1, 3, 6]"
3,Shai Gilgeous-Alexander,Thunder,Base,30.1,5.5,6.2,[],"[2, 7, 9]"
4,Michael Jordan,Bulls,Escolta,30.1,6.2,5.3,"[13, 14]","[10, 5, 12]"
5,LeBron James,Lakers,Alero,25.7,7.3,8.3,"[10, 12]","[8, 6, 4, 1]"
6,Kevin Durant,Suns,Alero,27.1,6.6,5.0,[],"[8, 5, 2, 0]"
7,Ja Morant,Grizzlies,Base,25.1,5.6,8.1,[],"[3, 8, 9, 13]"
8,Stephen Curry,Warriors,Base,26.4,4.5,5.1,[],"[5, 6, 1, 7]"
9,Anthony Edwards,Timberwolves,Escolta,25.9,5.4,5.1,[],"[3, 7, 11]"

### 6.3.2. Sorting DataFrames

Podemos elegir las columnas que queremos ordenar:

In [8]:
import pandas as pd

datos = {
    'Equipo': [
        'Nuggets', 'Mavericks', 'Bucks', 'Thunder', 'Bulls', 
        'Lakers', 'Suns', 'Grizzlies', 'Warriors', 'Timberwolves', 
        'Lakers', 'Spurs', 'Lakers', 'Bulls', 'Bulls'
    ],
    'Nombre': [
        'Nikola Jokic', 'Luka Doncic', 'Giannis Antetokounmpo', 'Shai Gilgeous-Alexander', 'Michael Jordan', 
        'LeBron James', 'Kevin Durant', 'Ja Morant', 'Stephen Curry', 'Anthony Edwards', 
        'Kobe Bryant', 'Victor Wembanyama', 'Shaquille O/Neal', 'Derrick Rose', 'Dennis Rodman'
    ],
    'Posicion': [
        'Pívot', 'Base', 'Ala-Pívot', 'Base', 'Escolta', 
        'Alero', 'Alero', 'Base', 'Base', 'Escolta', 
        'Escolta', 'Pívot', 'Pívot', 'Base', 'Ala-Pívot'
    ],
    'Puntos': [29.7, 33.9, 30.4, 30.1, 30.1, 25.7, 27.1, 25.1, 26.4, 25.9, 25.0, 21.4, 23.7, 17.7, 7.3],
    'Rebotes': [13.7, 9.2, 11.5, 5.5, 6.2, 7.3, 6.6, 5.6, 4.5, 5.4, 5.2, 10.6, 10.9, 3.3, 13.1],
    'Asistencias': [11.7, 9.8, 6.5, 6.2, 5.3, 8.3, 5.0, 8.1, 5.1, 5.1, 4.7, 3.9, 2.5, 5.2, 1.8],
    'Mismo_Equipo': [
        [], [], [], [], [13, 14], 
        [10, 12], [], [], [], [], 
        [5, 12], [], [5, 10], [4, 14], [4, 13]
    ],
    'Amigos': [
        [1, 2, 11], [0, 8, 11, 2], [0, 1, 3, 6], [2, 7, 9], [10, 5, 12],
        [8, 6, 4, 1], [8, 5, 2, 0], [3, 8, 9, 13], [5, 6, 1, 7], [3, 7, 11],
        [4, 13, 1], [0, 1, 9], [14, 4, 0], [7, 10, 8], [12, 5]
    ]
}

# Crear el DataFrame
df_nba = pd.DataFrame(datos)
sorted_df = df_nba.sort_values(by='Equipo', ascending= True)
sorted_df

,Equipo,Nombre,Posicion,Puntos,Rebotes,Asistencias,Mismo_Equipo,Amigos
2,Bucks,Giannis Antetokounmpo,Ala-Pívot,30.4,11.5,6.5,[],"[0, 1, 3, 6]"
4,Bulls,Michael Jordan,Escolta,30.1,6.2,5.3,"[13, 14]","[10, 5, 12]"
13,Bulls,Derrick Rose,Base,17.7,3.3,5.2,"[4, 14]","[7, 10, 8]"
14,Bulls,Dennis Rodman,Ala-Pívot,7.3,13.1,1.8,"[4, 13]","[12, 5]"
7,Grizzlies,Ja Morant,Base,25.1,5.6,8.1,[],"[3, 8, 9, 13]"
5,Lakers,LeBron James,Alero,25.7,7.3,8.3,"[10, 12]","[8, 6, 4, 1]"
10,Lakers,Kobe Bryant,Escolta,25.0,5.2,4.7,"[5, 12]","[4, 13, 1]"
12,Lakers,Shaquille O/Neal,Pívot,23.7,10.9,2.5,"[5, 10]","[14, 4, 0]"
1,Mavericks,Luka Doncic,Base,33.9,9.2,9.8,[],"[0, 8, 11, 2]"
0,Nuggets,Nikola Jokic,Pívot,29.7,13.7,11.7,[],"[1, 2, 11]"
11,Spurs,Victor Wembanyama,Pívot,21.4,10.6,3.9,[],"[0, 1, 9]"
6,Suns,Kevin Durant,Alero,27.1,6.6,5.0,[],"[8, 5, 2, 0]"
3,Thunder,Shai Gilgeous-Alexander,Base,30.1,5.5,6.2,[],"[2, 7, 9]"
9,Timberwolves,Anthony Edwards,Escolta,25.9,5.4,5.1,[],"[3, 7, 11]"
8,Warriors,Stephen Curry,Base,26.4,4.5,5.1,[],"[5, 6, 1, 7]"

### 6.3.3. Statistics on DataFrames

Podemos ver los maximos, minimos, sumatorio, media... de nuestro DataFrame

In [9]:
import pandas as pd

datos = {
    'Equipo': [
        'Nuggets', 'Mavericks', 'Bucks', 'Thunder', 'Bulls', 
        'Lakers', 'Suns', 'Grizzlies', 'Warriors', 'Timberwolves', 
        'Lakers', 'Spurs', 'Lakers', 'Bulls', 'Bulls'
    ],
    'Nombre': [
        'Nikola Jokic', 'Luka Doncic', 'Giannis Antetokounmpo', 'Shai Gilgeous-Alexander', 'Michael Jordan', 
        'LeBron James', 'Kevin Durant', 'Ja Morant', 'Stephen Curry', 'Anthony Edwards', 
        'Kobe Bryant', 'Victor Wembanyama', 'Shaquille O/Neal', 'Derrick Rose', 'Dennis Rodman'
    ],
    'Posicion': [
        'Pívot', 'Base', 'Ala-Pívot', 'Base', 'Escolta', 
        'Alero', 'Alero', 'Base', 'Base', 'Escolta', 
        'Escolta', 'Pívot', 'Pívot', 'Base', 'Ala-Pívot'
    ],
    'Puntos': [29.7, 33.9, 30.4, 30.1, 30.1, 25.7, 27.1, 25.1, 26.4, 25.9, 25.0, 21.4, 23.7, 17.7, 7.3],
    'Rebotes': [13.7, 9.2, 11.5, 5.5, 6.2, 7.3, 6.6, 5.6, 4.5, 5.4, 5.2, 10.6, 10.9, 3.3, 13.1],
    'Asistencias': [11.7, 9.8, 6.5, 6.2, 5.3, 8.3, 5.0, 8.1, 5.1, 5.1, 4.7, 3.9, 2.5, 5.2, 1.8],
    'Mismo_Equipo': [
        [], [], [], [], [13, 14], 
        [10, 12], [], [], [], [], 
        [5, 12], [], [5, 10], [4, 14], [4, 13]
    ],
    'Amigos': [
        [1, 2, 11], [0, 8, 11, 2], [0, 1, 3, 6], [2, 7, 9], [10, 5, 12],
        [8, 6, 4, 1], [8, 5, 2, 0], [3, 8, 9, 13], [5, 6, 1, 7], [3, 7, 11],
        [4, 13, 1], [0, 1, 9], [14, 4, 0], [7, 10, 8], [12, 5]
    ]
}

# Crear el DataFrame
df_nba = pd.DataFrame(datos)
media_puntos = df_nba['Puntos'].mean()
media_asistencias = df_nba['Asistencias'].mean()
media_rebotes = df_nba['Rebotes'].mean()
print(media_puntos, media_asistencias, media_rebotes)

25.299999999999997 5.946666666666667 7.906666666666666

## 6.4. Adding and Removing Columns

Podemos eliminar o incluso añadir columnas a nuestro DataFrame:

## 6.4.1. Adding a column

Podemos añadir columnas a nuestros DataFrames:

In [10]:
import pandas as pd

datos = {
    'Equipo': [
        'Nuggets', 'Mavericks', 'Bucks', 'Thunder', 'Bulls', 
        'Lakers', 'Suns', 'Grizzlies', 'Warriors', 'Timberwolves', 
        'Lakers', 'Spurs', 'Lakers', 'Bulls', 'Bulls'
    ],
    'Nombre': [
        'Nikola Jokic', 'Luka Doncic', 'Giannis Antetokounmpo', 'Shai Gilgeous-Alexander', 'Michael Jordan', 
        'LeBron James', 'Kevin Durant', 'Ja Morant', 'Stephen Curry', 'Anthony Edwards', 
        'Kobe Bryant', 'Victor Wembanyama', 'Shaquille O/Neal', 'Derrick Rose', 'Dennis Rodman'
    ],
    'Posicion': [
        'Pívot', 'Base', 'Ala-Pívot', 'Base', 'Escolta', 
        'Alero', 'Alero', 'Base', 'Base', 'Escolta', 
        'Escolta', 'Pívot', 'Pívot', 'Base', 'Ala-Pívot'
    ],
    'Puntos': [29.7, 33.9, 30.4, 30.1, 30.1, 25.7, 27.1, 25.1, 26.4, 25.9, 25.0, 21.4, 23.7, 17.7, 7.3],
    'Rebotes': [13.7, 9.2, 11.5, 5.5, 6.2, 7.3, 6.6, 5.6, 4.5, 5.4, 5.2, 10.6, 10.9, 3.3, 13.1],
    'Asistencias': [11.7, 9.8, 6.5, 6.2, 5.3, 8.3, 5.0, 8.1, 5.1, 5.1, 4.7, 3.9, 2.5, 5.2, 1.8],
    'Mismo_Equipo': [
        [], [], [], [], [13, 14], 
        [10, 12], [], [], [], [], 
        [5, 12], [], [5, 10], [4, 14], [4, 13]
    ],
    'Amigos': [
        [1, 2, 11], [0, 8, 11, 2], [0, 1, 3, 6], [2, 7, 9], [10, 5, 12],
        [8, 6, 4, 1], [8, 5, 2, 0], [3, 8, 9, 13], [5, 6, 1, 7], [3, 7, 11],
        [4, 13, 1], [0, 1, 9], [14, 4, 0], [7, 10, 8], [12, 5]
    ]
}

# Crear el DataFrame
df_nba = pd.DataFrame(datos)
#Añadimos una nueva columna:
df_nba['Jugador Activo'] = ['SI', 'SI', 'SI', 'SI', 'NO', 'SI', 'SI', 'SI', 'SI', 'SI', 'NO', 'SI', 'NO', 'NO', 'NO']
df_nba

,Equipo,Nombre,Posicion,Puntos,Rebotes,Asistencias,Mismo_Equipo,Amigos,Jugador Activo
0,Nuggets,Nikola Jokic,Pívot,29.7,13.7,11.7,[],"[1, 2, 11]",SI
1,Mavericks,Luka Doncic,Base,33.9,9.2,9.8,[],"[0, 8, 11, 2]",SI
2,Bucks,Giannis Antetokounmpo,Ala-Pívot,30.4,11.5,6.5,[],"[0, 1, 3, 6]",SI
3,Thunder,Shai Gilgeous-Alexander,Base,30.1,5.5,6.2,[],"[2, 7, 9]",SI
4,Bulls,Michael Jordan,Escolta,30.1,6.2,5.3,"[13, 14]","[10, 5, 12]",NO
5,Lakers,LeBron James,Alero,25.7,7.3,8.3,"[10, 12]","[8, 6, 4, 1]",SI
6,Suns,Kevin Durant,Alero,27.1,6.6,5.0,[],"[8, 5, 2, 0]",SI
7,Grizzlies,Ja Morant,Base,25.1,5.6,8.1,[],"[3, 8, 9, 13]",SI
8,Warriors,Stephen Curry,Base,26.4,4.5,5.1,[],"[5, 6, 1, 7]",SI
9,Timberwolves,Anthony Edwards,Escolta,25.9,5.4,5.1,[],"[3, 7, 11]",SI
10,Lakers,Kobe Bryant,Escolta,25.0,5.2,4.7,"[5, 12]","[4, 13, 1]",NO
11,Spurs,Victor Wembanyama,Pívot,21.4,10.6,3.9,[],"[0, 1, 9]",SI
12,Lakers,Shaquille O/Neal,Pívot,23.7,10.9,2.5,"[5, 10]","[14, 4, 0]",NO
13,Bulls,Derrick Rose,Base,17.7,3.3,5.2,"[4, 14]","[7, 10, 8]",NO
14,Bulls,Dennis Rodman,Ala-Pívot,7.3,13.1,1.8,"[4, 13]","[12, 5]",NO

### 6.4.2. Removing a column

Al igual que hemos hecho al añadir, pdoemos eliminar alguna columna, gracias al metodo drop()

In [11]:
import pandas as pd

datos = {
    'Equipo': [
        'Nuggets', 'Mavericks', 'Bucks', 'Thunder', 'Bulls', 
        'Lakers', 'Suns', 'Grizzlies', 'Warriors', 'Timberwolves', 
        'Lakers', 'Spurs', 'Lakers', 'Bulls', 'Bulls'
    ],
    'Nombre': [
        'Nikola Jokic', 'Luka Doncic', 'Giannis Antetokounmpo', 'Shai Gilgeous-Alexander', 'Michael Jordan', 
        'LeBron James', 'Kevin Durant', 'Ja Morant', 'Stephen Curry', 'Anthony Edwards', 
        'Kobe Bryant', 'Victor Wembanyama', 'Shaquille O/Neal', 'Derrick Rose', 'Dennis Rodman'
    ],
    'Posicion': [
        'Pívot', 'Base', 'Ala-Pívot', 'Base', 'Escolta', 
        'Alero', 'Alero', 'Base', 'Base', 'Escolta', 
        'Escolta', 'Pívot', 'Pívot', 'Base', 'Ala-Pívot'
    ],
    'Puntos': [29.7, 33.9, 30.4, 30.1, 30.1, 25.7, 27.1, 25.1, 26.4, 25.9, 25.0, 21.4, 23.7, 17.7, 7.3],
    'Rebotes': [13.7, 9.2, 11.5, 5.5, 6.2, 7.3, 6.6, 5.6, 4.5, 5.4, 5.2, 10.6, 10.9, 3.3, 13.1],
    'Asistencias': [11.7, 9.8, 6.5, 6.2, 5.3, 8.3, 5.0, 8.1, 5.1, 5.1, 4.7, 3.9, 2.5, 5.2, 1.8],
    'Mismo_Equipo': [
        [], [], [], [], [13, 14], 
        [10, 12], [], [], [], [], 
        [5, 12], [], [5, 10], [4, 14], [4, 13]
    ],
    'Amigos': [
        [1, 2, 11], [0, 8, 11, 2], [0, 1, 3, 6], [2, 7, 9], [10, 5, 12],
        [8, 6, 4, 1], [8, 5, 2, 0], [3, 8, 9, 13], [5, 6, 1, 7], [3, 7, 11],
        [4, 13, 1], [0, 1, 9], [14, 4, 0], [7, 10, 8], [12, 5]
    ]
}

# Crear el DataFrame
df_nba = pd.DataFrame(datos)
#Añadimos una nueva columna:
df_nba.drop('Posicion', axis= 1) #(Con el axis1, quitamos la columna)
df_nba

,Equipo,Nombre,Posicion,Puntos,Rebotes,Asistencias,Mismo_Equipo,Amigos
0,Nuggets,Nikola Jokic,Pívot,29.7,13.7,11.7,[],"[1, 2, 11]"
1,Mavericks,Luka Doncic,Base,33.9,9.2,9.8,[],"[0, 8, 11, 2]"
2,Bucks,Giannis Antetokounmpo,Ala-Pívot,30.4,11.5,6.5,[],"[0, 1, 3, 6]"
3,Thunder,Shai Gilgeous-Alexander,Base,30.1,5.5,6.2,[],"[2, 7, 9]"
4,Bulls,Michael Jordan,Escolta,30.1,6.2,5.3,"[13, 14]","[10, 5, 12]"
5,Lakers,LeBron James,Alero,25.7,7.3,8.3,"[10, 12]","[8, 6, 4, 1]"
6,Suns,Kevin Durant,Alero,27.1,6.6,5.0,[],"[8, 5, 2, 0]"
7,Grizzlies,Ja Morant,Base,25.1,5.6,8.1,[],"[3, 8, 9, 13]"
8,Warriors,Stephen Curry,Base,26.4,4.5,5.1,[],"[5, 6, 1, 7]"
9,Timberwolves,Anthony Edwards,Escolta,25.9,5.4,5.1,[],"[3, 7, 11]"
10,Lakers,Kobe Bryant,Escolta,25.0,5.2,4.7,"[5, 12]","[4, 13, 1]"
11,Spurs,Victor Wembanyama,Pívot,21.4,10.6,3.9,[],"[0, 1, 9]"
12,Lakers,Shaquille O/Neal,Pívot,23.7,10.9,2.5,"[5, 10]","[14, 4, 0]"
13,Bulls,Derrick Rose,Base,17.7,3.3,5.2,"[4, 14]","[7, 10, 8]"
14,Bulls,Dennis Rodman,Ala-Pívot,7.3,13.1,1.8,"[4, 13]","[12, 5]"

### 6.4.3. Adding a row

Gracias al método loc[], somos capaces de poder añadir una nueva fila, aunque debemos introducir la posicion (fila), en la que queremos añadir nuestra fila

In [12]:
import pandas as pd

datos = {
    'Equipo': [
        'Nuggets', 'Mavericks', 'Bucks', 'Thunder', 'Bulls', 
        'Lakers', 'Suns', 'Grizzlies', 'Warriors', 'Timberwolves', 
        'Lakers', 'Spurs', 'Lakers', 'Bulls', 'Bulls'
    ],
    'Nombre': [
        'Nikola Jokic', 'Luka Doncic', 'Giannis Antetokounmpo', 'Shai Gilgeous-Alexander', 'Michael Jordan', 
        'LeBron James', 'Kevin Durant', 'Ja Morant', 'Stephen Curry', 'Anthony Edwards', 
        'Kobe Bryant', 'Victor Wembanyama', 'Shaquille O/Neal', 'Derrick Rose', 'Dennis Rodman'
    ],
    'Posicion': [
        'Pívot', 'Base', 'Ala-Pívot', 'Base', 'Escolta', 
        'Alero', 'Alero', 'Base', 'Base', 'Escolta', 
        'Escolta', 'Pívot', 'Pívot', 'Base', 'Ala-Pívot'
    ],
    'Puntos': [29.7, 33.9, 30.4, 30.1, 30.1, 25.7, 27.1, 25.1, 26.4, 25.9, 25.0, 21.4, 23.7, 17.7, 7.3],
    'Rebotes': [13.7, 9.2, 11.5, 5.5, 6.2, 7.3, 6.6, 5.6, 4.5, 5.4, 5.2, 10.6, 10.9, 3.3, 13.1],
    'Asistencias': [11.7, 9.8, 6.5, 6.2, 5.3, 8.3, 5.0, 8.1, 5.1, 5.1, 4.7, 3.9, 2.5, 5.2, 1.8],
    'Mismo_Equipo': [
        [], [], [], [], [13, 14], 
        [10, 12], [], [], [], [], 
        [5, 12], [], [5, 10], [4, 14], [4, 13]
    ],
    'Amigos': [
        [1, 2, 11], [0, 8, 11, 2], [0, 1, 3, 6], [2, 7, 9], [10, 5, 12],
        [8, 6, 4, 1], [8, 5, 2, 0], [3, 8, 9, 13], [5, 6, 1, 7], [3, 7, 11],
        [4, 13, 1], [0, 1, 9], [14, 4, 0], [7, 10, 8], [12, 5]
    ]
}

# Crear el DataFrame
df_nba = pd.DataFrame(datos)
#Añadimos una nueva columna:
df_nba.loc[15] = ['DiscretasBasket', 'Ahmed Begga Hachlafi', 'Ala-Pívot', 99.9, 99.9 ,99.9, [], [4,5,8,10]] #(Con el axis1, quitamos la columna)
df_nba

,Equipo,Nombre,Posicion,Puntos,Rebotes,Asistencias,Mismo_Equipo,Amigos
0,Nuggets,Nikola Jokic,Pívot,29.7,13.7,11.7,[],"[1, 2, 11]"
1,Mavericks,Luka Doncic,Base,33.9,9.2,9.8,[],"[0, 8, 11, 2]"
2,Bucks,Giannis Antetokounmpo,Ala-Pívot,30.4,11.5,6.5,[],"[0, 1, 3, 6]"
3,Thunder,Shai Gilgeous-Alexander,Base,30.1,5.5,6.2,[],"[2, 7, 9]"
4,Bulls,Michael Jordan,Escolta,30.1,6.2,5.3,"[13, 14]","[10, 5, 12]"
5,Lakers,LeBron James,Alero,25.7,7.3,8.3,"[10, 12]","[8, 6, 4, 1]"
6,Suns,Kevin Durant,Alero,27.1,6.6,5.0,[],"[8, 5, 2, 0]"
7,Grizzlies,Ja Morant,Base,25.1,5.6,8.1,[],"[3, 8, 9, 13]"
8,Warriors,Stephen Curry,Base,26.4,4.5,5.1,[],"[5, 6, 1, 7]"
9,Timberwolves,Anthony Edwards,Escolta,25.9,5.4,5.1,[],"[3, 7, 11]"
10,Lakers,Kobe Bryant,Escolta,25.0,5.2,4.7,"[5, 12]","[4, 13, 1]"
11,Spurs,Victor Wembanyama,Pívot,21.4,10.6,3.9,[],"[0, 1, 9]"
12,Lakers,Shaquille O/Neal,Pívot,23.7,10.9,2.5,"[5, 10]","[14, 4, 0]"
13,Bulls,Derrick Rose,Base,17.7,3.3,5.2,"[4, 14]","[7, 10, 8]"
14,Bulls,Dennis Rodman,Ala-Pívot,7.3,13.1,1.8,"[4, 13]","[12, 5]"
15,DiscretasBasket,Ahmed Begga Hachlafi,Ala-Pívot,99.9,99.9,99.9,[],"[4, 5, 8, 10]"

### 6.4.4. Removing a row

Usando el mismo método que para eliminar columnas, podemos eliminar filas, ahora, sin  necesidad de poner "axis"

In [13]:
import pandas as pd

datos = {
    'Equipo': [
        'Nuggets', 'Mavericks', 'Bucks', 'Thunder', 'Bulls', 
        'Lakers', 'Suns', 'Grizzlies', 'Warriors', 'Timberwolves', 
        'Lakers', 'Spurs', 'Lakers', 'Bulls', 'Bulls'
    ],
    'Nombre': [
        'Nikola Jokic', 'Luka Doncic', 'Giannis Antetokounmpo', 'Shai Gilgeous-Alexander', 'Michael Jordan', 
        'LeBron James', 'Kevin Durant', 'Ja Morant', 'Stephen Curry', 'Anthony Edwards', 
        'Kobe Bryant', 'Victor Wembanyama', 'Shaquille O/Neal', 'Derrick Rose', 'Dennis Rodman'
    ],
    'Posicion': [
        'Pívot', 'Base', 'Ala-Pívot', 'Base', 'Escolta', 
        'Alero', 'Alero', 'Base', 'Base', 'Escolta', 
        'Escolta', 'Pívot', 'Pívot', 'Base', 'Ala-Pívot'
    ],
    'Puntos': [29.7, 33.9, 30.4, 30.1, 30.1, 25.7, 27.1, 25.1, 26.4, 25.9, 25.0, 21.4, 23.7, 17.7, 7.3],
    'Rebotes': [13.7, 9.2, 11.5, 5.5, 6.2, 7.3, 6.6, 5.6, 4.5, 5.4, 5.2, 10.6, 10.9, 3.3, 13.1],
    'Asistencias': [11.7, 9.8, 6.5, 6.2, 5.3, 8.3, 5.0, 8.1, 5.1, 5.1, 4.7, 3.9, 2.5, 5.2, 1.8],
    'Mismo_Equipo': [
        [], [], [], [], [13, 14], 
        [10, 12], [], [], [], [], 
        [5, 12], [], [5, 10], [4, 14], [4, 13]
    ],
    'Amigos': [
        [1, 2, 11], [0, 8, 11, 2], [0, 1, 3, 6], [2, 7, 9], [10, 5, 12],
        [8, 6, 4, 1], [8, 5, 2, 0], [3, 8, 9, 13], [5, 6, 1, 7], [3, 7, 11],
        [4, 13, 1], [0, 1, 9], [14, 4, 0], [7, 10, 8], [12, 5]
    ]
}

# Crear el DataFrame
df_nba = pd.DataFrame(datos)
#Añadimos una nueva columna:
for i in range(1,15,2):
    df_nba = df_nba.drop(i)
df_nba

,Equipo,Nombre,Posicion,Puntos,Rebotes,Asistencias,Mismo_Equipo,Amigos
0,Nuggets,Nikola Jokic,Pívot,29.7,13.7,11.7,[],"[1, 2, 11]"
2,Bucks,Giannis Antetokounmpo,Ala-Pívot,30.4,11.5,6.5,[],"[0, 1, 3, 6]"
4,Bulls,Michael Jordan,Escolta,30.1,6.2,5.3,"[13, 14]","[10, 5, 12]"
6,Suns,Kevin Durant,Alero,27.1,6.6,5.0,[],"[8, 5, 2, 0]"
8,Warriors,Stephen Curry,Base,26.4,4.5,5.1,[],"[5, 6, 1, 7]"
10,Lakers,Kobe Bryant,Escolta,25.0,5.2,4.7,"[5, 12]","[4, 13, 1]"
12,Lakers,Shaquille O/Neal,Pívot,23.7,10.9,2.5,"[5, 10]","[14, 4, 0]"
14,Bulls,Dennis Rodman,Ala-Pívot,7.3,13.1,1.8,"[4, 13]","[12, 5]"

### 6.5. Iterating over DataFrames

Gracias a el método iterrows(), podemos iterar en nuestros DataFrames:

In [14]:
import pandas as pd

datos = {
    'Equipo': [
        'Nuggets', 'Mavericks', 'Bucks', 'Thunder', 'Bulls', 
        'Lakers', 'Suns', 'Grizzlies', 'Warriors', 'Timberwolves', 
        'Lakers', 'Spurs', 'Lakers', 'Bulls', 'Bulls'
    ],
    'Nombre': [
        'Nikola Jokic', 'Luka Doncic', 'Giannis Antetokounmpo', 'Shai Gilgeous-Alexander', 'Michael Jordan', 
        'LeBron James', 'Kevin Durant', 'Ja Morant', 'Stephen Curry', 'Anthony Edwards', 
        'Kobe Bryant', 'Victor Wembanyama', 'Shaquille O/Neal', 'Derrick Rose', 'Dennis Rodman'
    ],
    'Posicion': [
        'Pívot', 'Base', 'Ala-Pívot', 'Base', 'Escolta', 
        'Alero', 'Alero', 'Base', 'Base', 'Escolta', 
        'Escolta', 'Pívot', 'Pívot', 'Base', 'Ala-Pívot'
    ],
    'Puntos': [29.7, 33.9, 30.4, 30.1, 30.1, 25.7, 27.1, 25.1, 26.4, 25.9, 25.0, 21.4, 23.7, 17.7, 7.3],
    'Rebotes': [13.7, 9.2, 11.5, 5.5, 6.2, 7.3, 6.6, 5.6, 4.5, 5.4, 5.2, 10.6, 10.9, 3.3, 13.1],
    'Asistencias': [11.7, 9.8, 6.5, 6.2, 5.3, 8.3, 5.0, 8.1, 5.1, 5.1, 4.7, 3.9, 2.5, 5.2, 1.8],
    'Mismo_Equipo': [
        [], [], [], [], [13, 14], 
        [10, 12], [], [], [], [], 
        [5, 12], [], [5, 10], [4, 14], [4, 13]
    ],
    'Amigos': [
        [1, 2, 11], [0, 8, 11, 2], [0, 1, 3, 6], [2, 7, 9], [10, 5, 12],
        [8, 6, 4, 1], [8, 5, 2, 0], [3, 8, 9, 13], [5, 6, 1, 7], [3, 7, 11],
        [4, 13, 1], [0, 1, 9], [14, 4, 0], [7, 10, 8], [12, 5]
    ]
}

# Crear el DataFrame
df_nba = pd.DataFrame(datos)
#Añadimos una nueva columna:
for index, row in df_nba.iterrows():
    print(index, row['Puntos'] ,row['Nombre'])

0 29.7 Nikola Jokic
1 33.9 Luka Doncic
2 30.4 Giannis Antetokounmpo
3 30.1 Shai Gilgeous-Alexander
4 30.1 Michael Jordan
5 25.7 LeBron James
6 27.1 Kevin Durant
7 25.1 Ja Morant
8 26.4 Stephen Curry
9 25.9 Anthony Edwards
10 25.0 Kobe Bryant
11 21.4 Victor Wembanyama
12 23.7 Shaquille O/Neal
13 17.7 Derrick Rose
14 7.3 Dennis Rodman

### 6.5.2. Iterating over columns

Con el método iteritems() podemos iterar al igual que en el apartado anterior, solo que con columnas:

In [15]:
import pandas as pd

datos = {
    'Equipo': [
        'Nuggets', 'Mavericks', 'Bucks', 'Thunder', 'Bulls', 
        'Lakers', 'Suns', 'Grizzlies', 'Warriors', 'Timberwolves', 
        'Lakers', 'Spurs', 'Lakers', 'Bulls', 'Bulls'
    ],
    'Nombre': [
        'Nikola Jokic', 'Luka Doncic', 'Giannis Antetokounmpo', 'Shai Gilgeous-Alexander', 'Michael Jordan', 
        'LeBron James', 'Kevin Durant', 'Ja Morant', 'Stephen Curry', 'Anthony Edwards', 
        'Kobe Bryant', 'Victor Wembanyama', 'Shaquille O/Neal', 'Derrick Rose', 'Dennis Rodman'
    ],
    'Posicion': [
        'Pívot', 'Base', 'Ala-Pívot', 'Base', 'Escolta', 
        'Alero', 'Alero', 'Base', 'Base', 'Escolta', 
        'Escolta', 'Pívot', 'Pívot', 'Base', 'Ala-Pívot'
    ],
    'Puntos': [29.7, 33.9, 30.4, 30.1, 30.1, 25.7, 27.1, 25.1, 26.4, 25.9, 25.0, 21.4, 23.7, 17.7, 7.3],
    'Rebotes': [13.7, 9.2, 11.5, 5.5, 6.2, 7.3, 6.6, 5.6, 4.5, 5.4, 5.2, 10.6, 10.9, 3.3, 13.1],
    'Asistencias': [11.7, 9.8, 6.5, 6.2, 5.3, 8.3, 5.0, 8.1, 5.1, 5.1, 4.7, 3.9, 2.5, 5.2, 1.8],
    'Mismo_Equipo': [
        [], [], [], [], [13, 14], 
        [10, 12], [], [], [], [], 
        [5, 12], [], [5, 10], [4, 14], [4, 13]
    ],
    'Amigos': [
        [1, 2, 11], [0, 8, 11, 2], [0, 1, 3, 6], [2, 7, 9], [10, 5, 12],
        [8, 6, 4, 1], [8, 5, 2, 0], [3, 8, 9, 13], [5, 6, 1, 7], [3, 7, 11],
        [4, 13, 1], [0, 1, 9], [14, 4, 0], [7, 10, 8], [12, 5]
    ]
}

# Crear el DataFrame
df_nba = pd.DataFrame(datos)
#Añadimos una nueva columna:
for column, values in df_nba.items():
    print(column, values.values)
    print('\n')

Equipo <StringArray>
[     'Nuggets',    'Mavericks',        'Bucks',      'Thunder',
        'Bulls',       'Lakers',         'Suns',    'Grizzlies',
     'Warriors', 'Timberwolves',       'Lakers',        'Spurs',
       'Lakers',        'Bulls',        'Bulls']
Length: 15, dtype: str


Nombre <StringArray>
[           'Nikola Jokic',             'Luka Doncic',
   'Giannis Antetokounmpo', 'Shai Gilgeous-Alexander',
          'Michael Jordan',            'LeBron James',
            'Kevin Durant',               'Ja Morant',
           'Stephen Curry',         'Anthony Edwards',
             'Kobe Bryant',       'Victor Wembanyama',
        'Shaquille O/Neal',            'Derrick Rose',
           'Dennis Rodman']
Length: 15, dtype: str


Posicion <StringArray>
[    'Pívot',      'Base', 'Ala-Pívot',      'Base',   'Escolta',     'Alero',
     'Alero',      'Base',      'Base',   'Escolta',   'Escolta',     'Pívot',
     'Pívot',      'Base', 'Ala-Pívot']
Length: 15, dtype: str


Puntos [29.7 33.9 30.4 30.1 30.1 25.7 27.1 25.1 26.4 25.9 25.  21.4 23.7 17.7
  7.3]


Rebotes [13.7  9.2 11.5  5.5  6.2  7.3  6.6  5.6  4.5  5.4  5.2 10.6 10.9  3.3
 13.1]


Asistencias [11.7  9.8  6.5  6.2  5.3  8.3  5.   8.1  5.1  5.1  4.7  3.9  2.5  5.2
  1.8]


Mismo_Equipo [list([]) list([]) list([]) list([]) list([13, 14]) list([10, 12])
 list([]) list([]) list([]) list([]) list([5, 12]) list([]) list([5, 10])
 list([4, 14]) list([4, 13])]


Amigos [list([1, 2, 11]) list([0, 8, 11, 2]) list([0, 1, 3, 6]) list([2, 7, 9])
 list([10, 5, 12]) list([8, 6, 4, 1]) list([8, 5, 2, 0])
 list([3, 8, 9, 13]) list([5, 6, 1, 7]) list([3, 7, 11]) list([4, 13, 1])
 list([0, 1, 9]) list([14, 4, 0]) list([7, 10, 8]) list([12, 5])]

## 6.6. Merging DataFrames

### 6.6.1. Merging two DataFrames

Podemos combinar dos dataframes en uno solo, gracias a la herramienta merge(), teniendo que mantener una de las columnas exactamente iguales entre dataframes (en mi caso la de nombre de los jugadores:

In [16]:
import pandas as pd

# 1. Datos básicos
datos1 = {
    'Nombre': ['LeBron James', 'Michael Jordan', 'Kobe Bryant', 'Stephen Curry', 'Nikola Jokic'],
    'Equipo': ['Lakers', 'Bulls', 'Lakers', 'Warriors', 'Nuggets'],
    'Puntos': [25.7, 30.1, 25.0, 26.4, 29.7]
}

# 2. Datos de rendimiento físico (usando los mismos Nombres)
datos2 = {
    'Nombre': ['LeBron James', 'Michael Jordan', 'Kobe Bryant', 'Stephen Curry', 'Nikola Jokic'],
    'Rebotes': [7.3, 6.2, 5.2, 4.5, 13.7],
    'Asistencias': [8.3, 5.3, 4.7, 5.1, 11.7]
}

df1 = pd.DataFrame(datos1)
df2 = pd.DataFrame(datos2)

# Ahora el merge sí funcionará porque encuentra los mismos nombres en todos
df = pd.merge(df1, df2, on='Nombre')
df

           Nombre    Equipo  Puntos  Rebotes  Asistencias
0    LeBron James    Lakers    25.7      7.3          8.3
1  Michael Jordan     Bulls    30.1      6.2          5.3
2     Kobe Bryant    Lakers    25.0      5.2          4.7
3   Stephen Curry  Warriors    26.4      4.5          5.1
4    Nikola Jokic   Nuggets    29.7     13.7         11.7

### 6.6.2. Merging multiple DataFrames

Una vez lo hemos visto con dos, la herramienta merge tambien acepta combinar más de dos dataframes

In [17]:
import pandas as pd

# 1. Datos básicos
datos1 = {
    'Nombre': ['LeBron James', 'Michael Jordan', 'Kobe Bryant', 'Stephen Curry', 'Nikola Jokic'],
    'Equipo': ['Lakers', 'Bulls', 'Lakers', 'Warriors', 'Nuggets'],
    'Puntos': [25.7, 30.1, 25.0, 26.4, 29.7]
}

# 2. Datos de rendimiento físico (usando los mismos Nombres)
datos2 = {
    'Nombre': ['LeBron James', 'Michael Jordan', 'Kobe Bryant', 'Stephen Curry', 'Nikola Jokic'],
    'Rebotes': [7.3, 6.2, 5.2, 4.5, 13.7],
    'Asistencias': [8.3, 5.3, 4.7, 5.1, 11.7]
}

# 3. Datos de relaciones (usando los mismos Nombres)
datos3 = {
    'Nombre': ['LeBron James', 'Michael Jordan', 'Kobe Bryant', 'Stephen Curry', 'Nikola Jokic'],
    'Amigos': [[8, 6], [10, 5], [4, 13], [5, 6], [1, 2]]
}

df1 = pd.DataFrame(datos1)
df2 = pd.DataFrame(datos2)
df3 = pd.DataFrame(datos3)

# Ahora el merge sí funcionará porque encuentra los mismos nombres en todos
df = pd.merge(df1, df2, on='Nombre')
df = pd.merge(df, df3, on='Nombre')

df

           Nombre    Equipo  Puntos  Rebotes  Asistencias   Amigos
0    LeBron James    Lakers    25.7      7.3          8.3   [8, 6]
1  Michael Jordan     Bulls    30.1      6.2          5.3  [10, 5]
2     Kobe Bryant    Lakers    25.0      5.2          4.7  [4, 13]
3   Stephen Curry  Warriors    26.4      4.5          5.1   [5, 6]
4    Nikola Jokic   Nuggets    29.7     13.7         11.7   [1, 2]

## 6.7. Grouping and Aggregating DataFrames

En el momento en el que en una columna, varias celdas se repitan, podemos agruparlas para analizar y ver sus datos:

### 6.7.1. Grouping and aggregating by one column

Gracias al método groupby() podemos agrupar nuestra columnas

In [18]:
import pandas as pd

df1 = pd.DataFrame(datos)
datos = {
    'Equipo': [
        'Nuggets', 'Mavericks', 'Bucks', 'Thunder', 'Bulls', 
        'Lakers', 'Suns', 'Grizzlies', 'Warriors', 'Timberwolves', 
        'Lakers', 'Spurs', 'Lakers', 'Bulls', 'Bulls'
    ],
    'Nombre': [
        'Nikola Jokic', 'Luka Doncic', 'Giannis Antetokounmpo', 'Shai Gilgeous-Alexander', 'Michael Jordan', 
        'LeBron James', 'Kevin Durant', 'Ja Morant', 'Stephen Curry', 'Anthony Edwards', 
        'Kobe Bryant', 'Victor Wembanyama', 'Shaquille O/Neal', 'Derrick Rose', 'Dennis Rodman'
    ],
    'Posicion': [
        'Pívot', 'Base', 'Ala-Pívot', 'Base', 'Escolta', 
        'Alero', 'Alero', 'Base', 'Base', 'Escolta', 
        'Escolta', 'Pívot', 'Pívot', 'Base', 'Ala-Pívot'
    ],
    'Puntos': [29.7, 33.9, 30.4, 30.1, 30.1, 25.7, 27.1, 25.1, 26.4, 25.9, 25.0, 21.4, 23.7, 17.7, 7.3],
    'Rebotes': [13.7, 9.2, 11.5, 5.5, 6.2, 7.3, 6.6, 5.6, 4.5, 5.4, 5.2, 10.6, 10.9, 3.3, 13.1],
    'Asistencias': [11.7, 9.8, 6.5, 6.2, 5.3, 8.3, 5.0, 8.1, 5.1, 5.1, 4.7, 3.9, 2.5, 5.2, 1.8],
    'Mismo_Equipo': [
        [], [], [], [], [13, 14], 
        [10, 12], [], [], [], [], 
        [5, 12], [], [5, 10], [4, 14], [4, 13]
    ],
    'Amigos': [
        [1, 2, 11], [0, 8, 11, 2], [0, 1, 3, 6], [2, 7, 9], [10, 5, 12],
        [8, 6, 4, 1], [8, 5, 2, 0], [3, 8, 9, 13], [5, 6, 1, 7], [3, 7, 11],
        [4, 13, 1], [0, 1, 9], [14, 4, 0], [7, 10, 8], [12, 5]
    ]
}

df = df1.groupby('Equipo')['Puntos'].sum()
print("Suma total de puntos por equipo:")

df

Suma total de puntos por equipo:

Equipo
Bucks           30.4
Bulls           55.1
Grizzlies       25.1
Lakers          74.4
Mavericks       33.9
Nuggets         29.7
Spurs           21.4
Suns            27.1
Thunder         30.1
Timberwolves    25.9
Warriors        26.4
Name: Puntos, dtype: float64

### 6.7.1. Grouping and aggregating by multiple columns

El método groupby() también admite varias columnas:

In [3]:
import pandas as pd

datos = {
    'Equipo': [
        'Nuggets', 'Mavericks', 'Bucks', 'Thunder', 'Bulls', 
        'Lakers', 'Suns', 'Grizzlies', 'Warriors', 'Timberwolves', 
        'Lakers', 'Spurs', 'Lakers', 'Bulls', 'Bulls'
    ],
    'Nombre': [
        'Nikola Jokic', 'Luka Doncic', 'Giannis Antetokounmpo', 'Shai Gilgeous-Alexander', 'Michael Jordan', 
        'LeBron James', 'Kevin Durant', 'Ja Morant', 'Stephen Curry', 'Anthony Edwards', 
        'Kobe Bryant', 'Victor Wembanyama', 'Shaquille O/Neal', 'Derrick Rose', 'Dennis Rodman'
    ],
    'Posicion': [
        'Pívot', 'Base', 'Ala-Pívot', 'Base', 'Escolta', 
        'Alero', 'Alero', 'Base', 'Base', 'Escolta', 
        'Escolta', 'Pívot', 'Pívot', 'Base', 'Ala-Pívot'
    ],
    'Puntos': [29.7, 33.9, 30.4, 30.1, 30.1, 25.7, 27.1, 25.1, 26.4, 25.9, 25.0, 21.4, 23.7, 17.7, 7.3],
    'Rebotes': [13.7, 9.2, 11.5, 5.5, 6.2, 7.3, 6.6, 5.6, 4.5, 5.4, 5.2, 10.6, 10.9, 3.3, 13.1],
    'Asistencias': [11.7, 9.8, 6.5, 6.2, 5.3, 8.3, 5.0, 8.1, 5.1, 5.1, 4.7, 3.9, 2.5, 5.2, 1.8],
    'Mismo_Equipo': [
        [], [], [], [], [13, 14], 
        [10, 12], [], [], [], [], 
        [5, 12], [], [5, 10], [4, 14], [4, 13]
    ],
    'Amigos': [
        [1, 2, 11], [0, 8, 11, 2], [0, 1, 3, 6], [2, 7, 9], [10, 5, 12],
        [8, 6, 4, 1], [8, 5, 2, 0], [3, 8, 9, 13], [5, 6, 1, 7], [3, 7, 11],
        [4, 13, 1], [0, 1, 9], [14, 4, 0], [7, 10, 8], [12, 5]
    ]
}


df1 = pd.DataFrame(datos)
df= df1.groupby('Equipo').agg({
    'Puntos': ['mean', 'max', 'min'],
    'Rebotes': 'sum'
})

df

                 Puntos             Rebotes
                   mean   max   min     sum
Equipo
Bucks         30.400000  30.4  30.4    11.5
Bulls         18.366667  30.1   7.3    22.6
Grizzlies     25.100000  25.1  25.1     5.6
Lakers        24.800000  25.7  23.7    23.4
Mavericks     33.900000  33.9  33.9     9.2
Nuggets       29.700000  29.7  29.7    13.7
Spurs         21.400000  21.4  21.4    10.6
Suns          27.100000  27.1  27.1     6.6
Thunder       30.100000  30.1  30.1     5.5
Timberwolves  25.900000  25.9  25.9     5.4
Warriors      26.400000  26.4  26.4     4.5

## 6.8. Reading and Writing DataFrames

Los DataFrames, los podemos convertir a otros formatos, y al mismo tiempo, podemos pasar de muchos tipos de formatos diversos, a un dataframe:

### 6.8.1. Reading a DataFrame from a CSV file

Podemos leer un DataFrame de un archivo CSV gracias al método read_csv():

(HE TENIDO QUE CREAR EL ARCHIVO NBA.csv ANTES DE PODER LEERLO)

In [4]:
import pandas as pd

df = pd.read_csv('NBA.csv')

# Display the DataFrame
df

,Equipo,Nombre,Posicion,Puntos,Rebotes,Asistencias,Mismo_Equipo,Amigos
0,Nuggets,Jokic,Pívot,29.7,13.7,11.7,[],"[1, 2]"
1,Mavericks,Doncic,Base,33.9,9.2,9.8,[],[]
2,Bucks,Antetokounmpo,Ala-Pívot,30.4,11.5,6.5,[],"[0, 1]"
3,Thunder,SGA,Base,30.1,5.5,6.2,[],[2]
4,Bulls,Jordan,Escolta,30.1,6.2,5.3,"[13, 14]",[]
5,Lakers,LeBron,Alero,25.7,7.3,8.3,"[10, 12]","[8, 1]"
6,Suns,KD,Alero,27.1,6.6,5.0,[],[3]
7,Grizzlies,Ja,Base,25.1,5.6,8.1,[],[3]
8,Warriors,Curry,Base,26.4,4.5,5.1,[],"[1, 7]"
9,Timberwolves,AntMan,Escolta,25.9,5.4,5.1,[],[3]
10,Lakers,Kobe,Escolta,25.0,5.2,4.7,"[5, 12]",[]
11,Spurs,Wemby,Pívot,21.4,10.6,3.9,[],[1]
12,Lakers,Shaq,Pívot,23.7,10.9,2.5,"[5, 10]",[14]
13,Bulls,DRose,Base,17.7,3.3,5.2,"[4, 14]","[7, 10, 8]"
14,Bulls,Rodman,Ala-Pívot,7.3,13.1,1.8,"[4, 13]",[]

### 6.8.2. Writing a DataFrame to a CSV file

Aqui podemos pasar de codigo, a un archivo CSV, con el to_csv:

In [5]:
import pandas as pd


datos = {
    'Equipo': [
        'Nuggets', 'Mavericks', 'Bucks', 'Thunder', 'Bulls', 
        'Lakers', 'Suns', 'Grizzlies', 'Warriors', 'Timberwolves', 
        'Lakers', 'Spurs', 'Lakers', 'Bulls', 'Bulls'
    ],
    'Nombre': [
        'Jokic', 'Doncic', 'Antetokounmpo', 'SGA', 'Jordan', 
        'LeBron', 'KD', 'Ja', 'Curry', 'AntMan', 
        'Kobe', 'Wemby', 'Shaq', 'DRose', 'Rodman'
    ],
    'Posicion': [
        'Pívot', 'Base', 'Ala-Pívot', 'Base', 'Escolta', 
        'Alero', 'Alero', 'Base', 'Base', 'Escolta', 
        'Escolta', 'Pívot', 'Pívot', 'Base', 'Ala-Pívot'
    ],
    'Puntos': [29.7, 33.9, 30.4, 30.1, 30.1, 25.7, 27.1, 25.1, 26.4, 25.9, 25.0, 21.4, 23.7, 17.7, 7.3],
    'Rebotes': [13.7, 9.2, 11.5, 5.5, 6.2, 7.3, 6.6, 5.6, 4.5, 5.4, 5.2, 10.6, 10.9, 3.3, 13.1],
    'Asistencias': [11.7, 9.8, 6.5, 6.2, 5.3, 8.3, 5.0, 8.1, 5.1, 5.1, 4.7, 3.9, 2.5, 5.2, 1.8],
    'Mismo_Equipo': [
        [], [], [], [], [13, 14], 
        [10, 12], [], [], [], [], 
        [5, 12], [], [5, 10], [4, 14], [4, 13]
    ],
    'Amigos': [
        [1, 2], [], [0, 1], [2], [],
        [8, 1], [3], [3], [1, 7], [3],
        [], [1], [14], [7, 10, 8], []
    ]
}

# 1. Creamos el DataFrame
df_nba = pd.DataFrame(datos)

df_nba.to_csv('NBA.csv', index=False)
print("Guardado")

Guardado

### 6.8.3. Reading a DataFrame from an Excel file

Tambien podemos leer y trabajar con archivos excel (xlsx):

(HE TENIDO QUE CREAR EL ARCHIVO data.xlsx ANTES DE PODER LEERLO)

In [6]:
import pandas as pd

# Read a DataFrame from an Excel file
df = pd.read_excel('data.xlsx')

# Display the DataFrame
df

,Equipo,Nombre,Posicion,Puntos,Rebotes,Asistencias,Mismo_Equipo,Amigos
0,Nuggets,Nikola Jokic,Pívot,29.7,13.7,11.7,[],"[1, 2, 11]"
1,Mavericks,Luka Doncic,Base,33.9,9.2,9.8,[],"[0, 8, 11, 2]"
2,Bucks,Giannis Antetokounmpo,Ala-Pívot,30.4,11.5,6.5,[],"[0, 1, 3, 6]"
3,Thunder,Shai Gilgeous-Alexander,Base,30.1,5.5,6.2,[],"[2, 7, 9]"
4,Bulls,Michael Jordan,Escolta,30.1,6.2,5.3,"[13, 14]","[10, 5, 12]"
5,Lakers,LeBron James,Alero,25.7,7.3,8.3,"[10, 12]","[8, 6, 4, 1]"
6,Suns,Kevin Durant,Alero,27.1,6.6,5.0,[],"[8, 5, 2, 0]"
7,Grizzlies,Ja Morant,Base,25.1,5.6,8.1,[],"[3, 8, 9, 13]"
8,Warriors,Stephen Curry,Base,26.4,4.5,5.1,[],"[5, 6, 1, 7]"
9,Timberwolves,Anthony Edwards,Escolta,25.9,5.4,5.1,[],"[3, 7, 11]"
10,Lakers,Kobe Bryant,Escolta,25.0,5.2,4.7,"[5, 12]","[4, 13, 1]"
11,Spurs,Victor Wembanyama,Pívot,21.4,10.6,3.9,[],"[0, 1, 9]"
12,Lakers,Shaquille O/Neal,Pívot,23.7,10.9,2.5,"[5, 10]","[14, 4, 0]"
13,Bulls,Derrick Rose,Base,17.7,3.3,5.2,"[4, 14]","[7, 10, 8]"
14,Bulls,Dennis Rodman,Ala-Pívot,7.3,13.1,1.8,"[4, 13]","[12, 5]"

### 6.8.4. Writing a DataFrame to an Excel file

No sólo podemos pasarlo a CSV, sino que tambien podemos pasarlo a excel gracias al to_excel()

In [7]:
import pandas as pd
#hace falta hacer pip install openpyxl

datos = {
    'Equipo': [
        'Nuggets', 'Mavericks', 'Bucks', 'Thunder', 'Bulls', 
        'Lakers', 'Suns', 'Grizzlies', 'Warriors', 'Timberwolves', 
        'Lakers', 'Spurs', 'Lakers', 'Bulls', 'Bulls'
    ],
    'Nombre': [
        'Nikola Jokic', 'Luka Doncic', 'Giannis Antetokounmpo', 'Shai Gilgeous-Alexander', 'Michael Jordan', 
        'LeBron James', 'Kevin Durant', 'Ja Morant', 'Stephen Curry', 'Anthony Edwards', 
        'Kobe Bryant', 'Victor Wembanyama', 'Shaquille O/Neal', 'Derrick Rose', 'Dennis Rodman'
    ],
    'Posicion': [
        'Pívot', 'Base', 'Ala-Pívot', 'Base', 'Escolta', 
        'Alero', 'Alero', 'Base', 'Base', 'Escolta', 
        'Escolta', 'Pívot', 'Pívot', 'Base', 'Ala-Pívot'
    ],
    'Puntos': [29.7, 33.9, 30.4, 30.1, 30.1, 25.7, 27.1, 25.1, 26.4, 25.9, 25.0, 21.4, 23.7, 17.7, 7.3],
    'Rebotes': [13.7, 9.2, 11.5, 5.5, 6.2, 7.3, 6.6, 5.6, 4.5, 5.4, 5.2, 10.6, 10.9, 3.3, 13.1],
    'Asistencias': [11.7, 9.8, 6.5, 6.2, 5.3, 8.3, 5.0, 8.1, 5.1, 5.1, 4.7, 3.9, 2.5, 5.2, 1.8],
    'Mismo_Equipo': [
        [], [], [], [], [13, 14], 
        [10, 12], [], [], [], [], 
        [5, 12], [], [5, 10], [4, 14], [4, 13]
    ],
    'Amigos': [
        [1, 2, 11], [0, 8, 11, 2], [0, 1, 3, 6], [2, 7, 9], [10, 5, 12],
        [8, 6, 4, 1], [8, 5, 2, 0], [3, 8, 9, 13], [5, 6, 1, 7], [3, 7, 11],
        [4, 13, 1], [0, 1, 9], [14, 4, 0], [7, 10, 8], [12, 5]
    ]
}
df = pd.DataFrame(datos)

# Write the DataFrame to an Excel file
df.to_excel('data.xlsx', index=False)